### PR TITLE
Fixing aura configuration for return possibility to compile the Core project

### PR DESCRIPTION
**Pull request by sinitcin**
1. Adding MaxAuthorities

```rust
parameter_types! {
    pub const MaxAuthorities: u32 = 1000;
}

impl pallet_aura::Config for Runtime {
    type AuthorityId = AuraId;
    type DisabledValidators = ();
    type MaxAuthorities = MaxAuthorities;
}
```

2. I had an error in `impl sp_consensus_aura::AuraApi<Block, AuraId> for Runtime {` and I fixed by adding `to_vec()` but not sure is it correct or not:

```rust
        fn authorities() -> Vec<AuraId> {
            Aura::authorities().to_vec()
        }
```

### CODE REVIEW

**Review by altonen — CHANGES_REQUESTED** [review]
This builds fine on my machine but I have two concerns. Firstly, why is Ben's merge commit from staging to master being committed to staging? And secondly, you forgot to sign your commit.

**Comment by muursh** [comment]
Builds fine for me too on Ubutnu, Fedora and MacOS. Haven't tried Windows but I'm just booting to try it now.

@sinitcin you wanted a Cargo.lock on git right? Maybe you could add it to this PR.

**Comment by sinitcin** [comment]
@b-yap Is it MaxAuthorities = 1000 good or shall be more?

**Comment by sinitcin** [comment]
> me too on Ubutnu, Fedora and MacOS. Haven't tried Windows but I'm just booting to try it now.
> 
> @sinitcin you wanted a Cargo.lock on git right? Maybe you could add it to this PR.

Yep, let me add it

**Comment by iljakuklic** [comment]
I see a lot of formatting changes that make it difficult to tease out the substantial code changes.

**Comment by sinitcin** [comment]
> This builds fine on my machine but I have two concerns. Firstly, why is Ben's merge commit from staging to master being committed to staging? And secondly, you forgot to sign your commit.

As far as I see, Ben's commit was to update the main branch and in my MR just github verify compatibility for his commit.

**Comment by sinitcin** [comment]
> I see a lot of formatting changes that make it difficult to tease out the substantial code changes.

@iljakuklic There wasn't substantial code changes in the commit =) All that was changed under the title.

**Comment by iljakuklic** [comment]
> > I see a lot of formatting changes that make it difficult to tease out the substantial code changes.
> 
> @iljakuklic There wasn't substantial code changes in the commit =) All that was changed under the title.

Well I meant any non-formatting changes but I did manage to have a look in git using `--ignore-space-change` and it looks fine. Also I don't know what the `core.iml` file is for.

**Comment by sinitcin** [comment]
> Also I don't know what the `core.iml` file is for.
@iljakuklic Oops, my bad. It's Intellij Idea project file. I'll remove it and add to `.gitignore`

**Comment by b-yap** [comment]
> @b-yap Is it MaxAuthorities = 1000 good or shall be more?

that's alright. It can easily be changed in the future.

**Comment by altonen** [comment]
I still don't understand why the merge commit would have to be included to staging and the commits are missing signatures but if others are OK with these changes, I don't mind.

**Review by muursh — APPROVED** [review]

**Comment by muursh** [comment]
I'd rather the commits were signed but given the convo here and on slack we can be pretty certain who the author is :smile:

**Review by altonen — APPROVED** [review]

**Comment by sinitcin** [comment]
> I'd rather the commits were signed but given the convo here and on slack we can be pretty certain who the author is smile

@altonen has explained a bit more in DM and remind me how to sign commits. I agree with him, in the next time, I'll sign commits =)

**Pull request merged**
